Sprint1/step2
kirillchistov/react-burger pull request #14
Opened 2023-02-16 15:00 UTC by kirillchistov

- [ ] Пул-реквест создан из ветки sprint-1/step-2 в main .
- [ ] Проект создан через CRA с флагом --template со значением typescript
- [ ] Сборка и запуск проекта выполняются без ошибок.
- [ ] Установлен пакет @ya.praktikum/react-developer-burger-ui-components .
- [ ] Есть директория components с компонентами и стилями: App , AppHeader , BurgerIngredients , BurgerConstructor , Modal , ModalOverlay , OrderDetails , IngredientDetails
- [ ] Сторонние шрифты или изображения хранятся в папках fonts и images ;
- [ ] Файл README.md (надо еще украсить)
- [ ] Файл .gitignore (надо дополнить)
- [ ] Стили портированы как модули. (надо подумать, что портировать в глобальную область видимости)
- [ ] Имена переменных и функций написаны в camelCase (перепроверить надо);
- [ ] Имена классов и функциональных компонент — существительные с прописной буквы
- [ ] имена переменных — существительные (...)
- [ ] имя функции отражает то, что она делает.
- [ ] Корректно выполняются запросы к API:
- [ ] URL-адрес домена вынесен в отдельную константу;
- [ ] есть проверка успешности выполнения запроса;
- [ ] цепочка обработки промисов завершается блоком catch .
- [ ] Разметка портирована в JSX:
- [ ] разметка заключена в ( ) ;
- [ ] разметка вынесена в соответствующие ей компоненты.
- [ ] хуки не используются внутри условных блоков;
- [ ] хуки вызываются в основной функции компонента;
- [ ] при использовании классовых компонентов эффекты описаны внутри методов жизненного цикла (нет классов).
- [ ] Для компонентов с пропсами описан propTypes . Если в качестве пропсов передается объект или массив объектов, то в propTypes описана структура этого объекта (это стоит еще проверить)
- [ ] компонент AppHeader использует UI-компоненты из библиотеки: логотип, иконки, типографику, систему отступов;
- [ ] компонент BurgerIngredients отображает список полученных с сервера ингредиентов. 
- [ ] В BurgerIngredients используются UI-компоненты из библиотеки: счётчики, иконки, переключатели, типографика, система отступов;
- [ ] компонент BurgerConstructor отображает список ингредиентов, добавленных в бургер, полную стоимость и кнопку офоџџрмления заказа. 
- [ ] В BurgerConstructor используются UIкомпоненты из библиотеки: ConstructorElement , иконки, кнопка, типографика, система отступов;
- [ ] компонент IngredientDetails при открытии содержит данные, полученные от API с описанием конкретного ингредиента и использует UI-компоненты из библиотеки: иконки, типографику; 
- [ ] компонент OrderDetails содержит тестовые данные и использует UI-компоненты из библиотеки: иконки, типографику.
- [ ] есть компонент Modal — шапка с заголовком и иконкой закрытия;
- [ ] содержимое модального окна передается в компонент Modal как children ;
- [ ] есть компонент ModalOverlay — фоновая подложка под модальным окном;
- [ ] модальное окно с описанием ингредиента открывается при клике по ингредиенту;
- [ ] модальное окно с описанием заказа открывается при клике по кнопке «Оформить заказ»;
- [ ] модальные окна закрываются при клике на крестик, на ModalOverlay или нажатием на клавишу "Esc";
- [ ] логика навешивания и удаления обработчиков события нажатия клавиши "Esc" описана в
- [ ] компоненте Modal ;
- [ ] в компоненте Modal используется портал;
- [ ] использованы UI-компоненты из библиотеки: иконки, типографика.
- [ ] Запрос к API за информацией об ингредиентах работает корректно и выполняется единожды при монтировании компонента App

2023-02-16 15:43 UTC, andryxxa93 reviewed
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Что понравилось:
- Запрос находится в отдельном файле
- Элементы хедера сделаны ссылками
- Есть проверка успешности запроса

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

- [x] Проект не собирается, т.к. не совпадает регистр букв в названии файла и при импорте. Проверьте, что в системе контроля версий правильный регистр и при необходимости измените https://noteskeeper.ru/heritage/672/
<img width="1440" alt="Снимок экрана 2023-02-16 в 18 27 18" src="https://user-images.githubusercontent.com/60173362/219410873-8ea78890-c0f5-4fe7-9495-5ddee8fd72b6.png">

- [ ] Есть некоторые проблемы с версткой элементов внутри конструктора. Иконка должна быть напротив ингредиента. Пожалуйста посмотрите как в макете.
<img width="476" alt="Снимок экрана 2023-02-16 в 18 29 42" src="https://user-images.githubusercontent.com/60173362/219411496-e4fce5af-52b0-40a6-bb4b-cedcf4a15406.png">

- [x] В проекте есть два файла `App` - один находится на уровне компонентов, другой на уровне `src`. 
- [x] Необходимо удалить `App.test.tsx` так он не используется в проекте. И у файла index.scss есть два файла со стилями, ненужный следует удалить.
- [ ] Все файлы с пропсами должны иметь `propTypes`
- [ ] Дописать `isRequired` там где не хватает - иначе не будет ошибки если пропс не передан
- [ ] Доделать типизацию получаемого списка ингредиентов
- [ ] Дописать отсутствующие поля у ингредиента
- [ ] Инлайн-стилей style={{не должно быть в проекте, если они не меняются динамически в коде компонента. 

Более подробно описание проблемы смотрите комментарии в pull request.

**Можно лучше**
- В проекте присутствует много закоментированого кода, необходимо или удалить его или разкоментировать
- Пока в проекте не используется `typescript` все файлы должны иметь расширение `jsx` или `js`.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-02-16 15:43 UTC, andryxxa93 commented on src/components/App/App.jsx
> +    return null
**Можно лучше**
Пока ингредиенты загружаются можно показывать лоадеры - их можно взять отсюда https://loading.io/css/

2023-02-16 15:43 UTC, andryxxa93 commented on src/components/App/App.module.css
> +.mainContainer {
**Можно улучшить**
Ненужный код лучше удалять

2023-02-16 15:43 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +const BurgerIngredients = (props) => {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2023-02-16 15:43 UTC, andryxxa93 commented on src/utils/data.js
> +export const ingredientsData = [
**Можно лучше**
Файл больше не нужен - его можно удалить

2023-02-16 15:43 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +      document.body.removeEventListener('keydown', closeByEscape);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-02-16 15:43 UTC, andryxxa93 commented on src/components/ingredient-filter/ingredient-filter.jsx
> +  ingredients: PropTypes.arrayOf(PropTypes.object).isRequired,
**Необходимо исправить**
Сейчас получается, что под `ingredients` может прийти массив любого содержания, но на самом деле это не так. Необходимо использовать тип, который у вас уже написан, но почему-то закоментирован `ingredientType`

Вот так:
`  ingredients: PropTypes.arrayOf(ingredientType.isRequired).isRequired,`

2023-02-16 15:43 UTC, andryxxa93 commented on src/utils/types.js
> +export const ingredientType = PropTypes.shape({
**Необходимо исправить**
Необходимо дописать отсутствующие поля, все те, что уже указаны в закоменченом ниже участке кода. Так же не забудьте проставить для каждого поля `isRequired`

2023-02-19 07:10 UTC, andryxxa93 requested changes
Всё отлично, только у вас в проекте вы используете правильную типизацию, но почему-то закоментировали её. Исправьте этот момент и ваша работа будет принята. Эти моменты отмечены комментариями в pull-request.

2023-02-19 07:10 UTC, andryxxa93 commented on src/components/tabs/tabs.jsx
> +    <div style={`${TabsStyle.mainContainer}`}>
**Необходимо исправить**
Необходимо использовать `className` а не `style`.

2023-02-19 07:10 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +};
**Необходимо исправить**
Тут уже необходимо использовать объявленный вами тип. Проверьте во всех подобных местах.
`BurgerConstructor.propTypes = {
  ingredientsData: PropTypes.arrayOf(ingredientType).isRequired,
};`

2023-02-19 07:10 UTC, andryxxa93 commented on src/components/ingredient-details/ingredient-details.jsx
> +  image: PropTypes.string.isRequired,
**Необходимо исправить**
Тут вы почему-то закоментировали правильную типизацию

2023-02-19 07:53 UTC, kirillchistov commented on src/components/tabs/tabs.jsx
> +    <div style={`${TabsStyle.mainContainer}`}>
Спасибо, это докатил в последнем коммите

2023-02-19 07:56 UTC, kirillchistov commented on src/components/burger-constructor/burger-constructor.jsx
> +};
Спасибо!

2023-02-19 09:03 UTC, kirillchistov commented on src/components/ingredient-details/ingredient-details.jsx
> +  image: PropTypes.string.isRequired,
Закомментировал, потому что получал undefined ошибку в консоли в таком виде и никак не могу собрать деконструкцию, чтобы использовать типизацию ingredientType из /utils/types ((

Странно, но в таком виде нет ошибки в консоли:
IngredientDetails.propTypes = ingredientType.isRequired;
Корректной ли будет такая запись?

2023-02-19 15:50 UTC, andryxxa93 approved these changes
Отлично! Все замечания исправлены, вы отлично поработали, работа принята.
Желаю удачного продолжения обучения!

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

2023-02-19 15:50 UTC, andryxxa93 commented on src/components/ingredient-details/ingredient-details.jsx
> +IngredientDetails.propTypes = ingredientType.isRequired;
Это вполне корректная запись ))

2023-02-19 15:50 UTC, andryxxa93 commented on src/components/ingredient-item/ingredient-item.jsx
>    item: PropTypes.object.isRequired,
**Можно лучше**
Тут необходимо вот так: 
```
IngredientItem.propTypes = {
     item: ingredientType
};
```

2023-02-22 15:54 UTC, merged

2023-02-22 15:55 UTC, kirillchistov commented
Спасибо