Sprint 2/step 1
kirillchistov/react-burger pull request #22
Opened 2023-02-27 19:48 UTC by kirillchistov

Спасибо заранее за ревью и рекомендации по улучшению. С useReducer пока не совсем разобрался, костыльно сделал.

2023-02-27 20:33 UTC, andryxxa93 requested changes
Здравствуйте! Отличная работа!
Что понравилось:
- Использовали useMemo
- Использовали useReducer 
- Хорошо разобрались с Context API.


**Необходимо исправить**
- Необходимо избавиться от горизонтального скролла внутри конструктора.
<img width="574" alt="Снимок экрана 2023-02-27 в 23 27 43" src="https://user-images.githubusercontent.com/60173362/221678213-e1f22be6-f6ff-4a80-b00f-df011f2caf91.png">


**Можно лучше**
- В проекте много console.log и закоментированого кода - обычно перед проверкой их необходимо удалять.

Удачных правок!

2023-02-28 18:44 UTC, kirillchistov commented
Спасибо за ревью! 
С адаптивностью в  проекте пока вообще не очень ).
Но я никак не могу воспроизвести полосу прокрутки ни на одном устройстве или браузере. Вроде бы нет там overflow по оси X. Можно ли уточнить в каком браузере на каком устройстве и в каком масштабе такой эффект? 
Еще лучше показать на скрине с консолью, чтобы было видно какие стили применяются к элементу, если могу об таком просить @andryxxa93 ? Спасибо 
PS. При этом на скрине не видна полоса вертикальной прокрутки для конструктора (видна для блока ингредиентов)... Или это просто такой скриншот?

2023-03-01 06:12 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-01 06:13 UTC, andryxxa93 commented
> Спасибо за ревью! С адаптивностью в проекте пока вообще не очень ). Но я никак не могу воспроизвести полосу прокрутки ни на одном устройстве или браузере. Вроде бы нет там overflow по оси X. Можно ли уточнить в каком браузере на каком устройстве и в каком масштабе такой эффект? Еще лучше показать на скрине с консолью, чтобы было видно какие стили применяются к элементу, если могу об таком просить @andryxxa93 ? Спасибо PS. При этом на скрине не видна полоса вертикальной прокрутки для конструктора (видна для блока ингредиентов)... Или это просто такой скриншот?

После изменений в стилях скролл исчез 👍

2023-03-04 05:51 UTC, merged