Sprint 2/step 2
kirillchistov/react-burger pull request #32
Opened 2023-03-02 23:13 UTC by kirillchistov

Спасибо заранее за ревью и рекомендации по улучшению

2023-03-03 02:51 UTC, andryxxa93 requested changes
Здравствуйте! Отличный проект 👍 
Что понравилось:
- Хорошо работает `Dnd`
- Хорошо организовано хранилище
- Созданы все необходимые экшены
- Используются `useMemo` и `useCallback`

Что необходимо исправить:
- Не стоит позволять юзеру делать пустой заказ. Если конструктор пуст, то лучше скрывать или дизейблить кнопку заказа.
- Если ингредиент не добавлен в конструктор показывать счетчик со значением - "0"  не нужно.
-  Если добавить в конструктор много ингредиентов происходит проблема с версткой.
<img width="556" alt="Снимок экрана 2023-03-03 в 05 40 03" src="https://user-images.githubusercontent.com/60173362/222617805-acbe59c1-e2bf-40cd-a225-98fc04365d59.png">
- В некоторых компонентах в `propTypes` указаны не все пропсы.
- Контекст больше не нужен, его можно удалить.


В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-03 02:51 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +  const { orderData, orderNumber } = useSelector((state) => state.order);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-03-03 02:51 UTC, andryxxa93 commented on src/components/ingredient-category/ingredient-category.jsx
> +IngredientCategory.propTypes = {
**Необходимо исправить**
в этом и других `propTypes ` указаны не все пропсы. Пожалуйста проверьте во всем проекте.

2023-03-03 20:40 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-04 05:51 UTC, merged

2023-03-04 05:51 UTC, kirillchistov commented
Спасибо!