Sprint 3/step 1
kirillchistov/react-burger pull request #51
Opened 2023-03-13 21:14 UTC by kirillchistov

Спасибо заранее за ревью!

2023-03-13 22:59 UTC, andryxxa93 requested changes
Здравствуйте! Отличный проект 👍 
Что понравилось:
- Реализован механизм защиты роутов от авторизованных и не авторизованных юзеров.
- Предусмотрены редиректы после авторизационных действий.
- Авторизация не сбрасывается при перезагрузке страницы.


Что необходимо исправить:
- При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.
<img width="1440" alt="Снимок экрана 2023-03-14 в 01 41 48" src="https://user-images.githubusercontent.com/60173362/224849424-4b4cbcad-17c3-4475-87da-f805b9467502.png">

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-13 22:59 UTC, andryxxa93 commented on src/app.jsx
> +      <Route path='/profile/orders' element={
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-03-13 22:59 UTC, andryxxa93 commented on src/components/ingredient-item/ingredient-item.jsx
>  export const IngredientItem = ( { ingredientData } ) => {
**Можно лучше**

используйте для компонентов обертку React.memo, которая позволяет сократить количество лишних рендеров и улучшить производительность

Например:

```
const SomeComponent = () => {
  return (
     ...........
  );
};

export default React.memo(SomeComponent);
```

https://ru.reactjs.org/docs/react-api.html#reactmemo
https://habr.com/ru/company/plarium/blog/442116/

2023-03-13 22:59 UTC, andryxxa93 commented on src/services/actions/auth-actions.js
> +        setCookies(res.accessToken, res.refreshToken);
**Можно лучше**

Чтобы приходящий с сервера токен заносился всегда по пути "/" в куку, нужно в функцию setCookies передавать как значение параметра props аргумент {path="/"}:
setCookie('name', value, { path: '/' }).
Об этом можно прочитать здесь: https://learn.javascript.ru/cookie
Уничтожать токен при логауте пользователя нужно также по пути path: '/'.

2023-03-14 15:23 UTC, kirillchistov commented on src/app.jsx
> +      <Route path='/profile/orders' element={
Добрый день! Спасибо за ревью и комментариии. По поводу роутов в константах - думал об этом и даже сделал объект https://github.com/kirillchistov/react-burger/blob/sprint-3/step-1/src/utils/constants.js 
Но уж больно громоздко выглядит такая оптимизация (длина константы vs. длина роута)! Есть ли подсказка на более эстетичный способ?

2023-03-14 15:31 UTC, kirillchistov commented on src/app.jsx
> +      <Route path='/profile/orders' element={
По критическому багу "запрос обновления токена и повторить запрос" 
Cделал, но, уверен, что не корректно, теперь refresh-токен лежит в сессионной куке. То есть, по завершении сессии, пользователь переводится на логин (не может ничего редактировать с протухшим токеном). Вроде в ТЗ было про session cookie.
Пока не сообразил как это правильней оптимизировать так, чтобы не отправлять при каждом запросе доп.запрос на refresh токена. Корректна ли такая реализация или правильней всего решить это другим способом?

2023-03-14 15:34 UTC, kirillchistov commented on src/services/actions/auth-actions.js
> +        setCookies(res.accessToken, res.refreshToken);
Добавил внутри функций так: 
`export const setCookie = (name, value, props) => {
   props = {...props, path: '/'};
...
`

`export const deleteCookie = (name) => {
  setCookie(name, null, { expires: -1, path: '/' });
}`
Корректна ли такая запись?

2023-03-14 15:56 UTC, kirillchistov commented on src/components/ingredient-item/ingredient-item.jsx
>  export const IngredientItem = ( { ingredientData } ) => {
Добавил, спасибо!

2023-03-14 19:13 UTC, kirillchistov commented
Уже вижу, что поторопился и накосячил c проверкой на необходимость обновление и обновлением токена. Попробую оперативно исправить, не успев потратить попытку )

2023-03-15 05:47 UTC, andryxxa93 commented on src/app.jsx
> +      <Route path='/profile/orders' element={
Вы можете создать функцию обертку для запросов где возможно потребуется обновление токена. 
Например что-то такое.
```
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      setCookie("accessToken", refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};


export const updateUser = (user) => {
  return fetchWithRefresh(`${BURGER_API_URL}/auth/user`, {
    method: "PATCH",
    headers: {
      "Content-Type": "application/json;charset=utf-8",
      authorization: getCookie("accessToken"),
    },
    body: JSON.stringify(user),
  });
};

```

2023-03-15 05:53 UTC, andryxxa93 commented
- После авторизации падает приложение с ошибкой. 
<img width="1439" alt="Снимок экрана 2023-03-15 в 08 40 09" src="https://user-images.githubusercontent.com/60173362/225217350-eac4c7ba-593d-4d21-b04c-42f2dba85ffe.png">

- Условие `if (err.message === "jwt expired") ` никогда не сработает потому что функция `checkResponse` передает в  поле `message` - `undefined`.

2023-03-15 05:55 UTC, andryxxa93 commented on src/app.jsx
> +      <Route path='/profile/orders' element={
> Добрый день! Спасибо за ревью и комментариии. По поводу роутов в константах - думал об этом и даже сделал объект https://github.com/kirillchistov/react-burger/blob/sprint-3/step-1/src/utils/constants.js Но уж больно громоздко выглядит такая оптимизация (длина константы vs. длина роута)! Есть ли подсказка на более эстетичный способ?

Вполне отличный способ, так обычно в проектах и используют.

2023-03-15 19:20 UTC, kirillchistov commented on src/app.jsx
> +      <Route path='/profile/orders' element={
Вроде получилось реализовать fetchWithRefresh. Прошу ревью. Спасибо!

2023-03-16 06:37 UTC, andryxxa93 commented
- Обновление токена всё равно не работает. По двум причинам.

1. Условие `if (err.message === "jwt expired")`  никогда не сработает потому что функция checkResponse передает в поле message - undefined. В объекте res нет поля message. 
Вам необходимо иначе возвращать ошибку из `checkResponse` 
` return res.ok ? res.json() : res.json().then((err) => Promise.reject(err))`;

2. При обновлении токена в тело запроса должен передаваться `refreshToken`, а туда передается `null` 

<img width="1440" alt="Снимок экрана 2023-03-16 в 09 32 36" src="https://user-images.githubusercontent.com/60173362/225534023-2cafe962-f06a-490e-8d51-af32df54b82e.png">

2023-03-16 15:01 UTC, kirillchistov commented
Спасибо! Вроде разобрался, хоть и с трудом. А можно подсказку: как избавиться от 403 ошибки в консоли при обновлении профиля с протухшим токеном. Обновление пары через refreshToken срабатывает, но в консоль ошибка прилетает все-таки...  @andryxxa93  можете, пожалуйста, дать подсказку?

2023-03-16 20:47 UTC, andryxxa93 commented
> Спасибо! Вроде разобрался, хоть и с трудом. А можно подсказку: как избавиться от 403 ошибки в консоли при обновлении профиля с протухшим токеном. Обновление пары через refreshToken срабатывает, но в консоль ошибка прилетает все-таки... @andryxxa93 можете, пожалуйста, дать подсказку?

Насколько я знаю никак - так работает промис в случае ошибки. Это на самом деле хорошо, что она туда попадает - дополнительная информация в случае ошибки полезная вещь.

2023-03-16 20:49 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-16 21:45 UTC, merged

2023-03-16 21:45 UTC, kirillchistov commented
Спасибо!